tutordiscovery/patches/nginx-extra
When trying to setup an image in a course metadata, nginx can't resolve the request to fetch the file.
One way to reproduce this issue, is to setup discovery, then go to http://discovery.localhost/admin/course_metadata/course/1/change/ change the course image and try to access the uploaded image, in my case: http://discovery.localhost/media/media/course/image/5d07b45a-1da2-4f23-8c65-3f81263bb024-34cfe8f2a782.jpg will fail to retrieve.
I _think_ that this is because the nginx location for media is missing.
I didn't confirm this yet, but I think that ecommerce will have the same issue as we don't have a mapping for /media, if you configure stripe it will try to fetch the image url that was received from discovery service, in my local testing is trying to fetch from ecommerce, so it will …
=> Adding media location.

tutordiscovery/patches/local-docker-compose-nginx-aliases
Add local nginx aliase to allow access discovery service through
discovery.local.overhang.io when running locally.
=> Add local nginx aliase.

tutordiscovery/templates/discovery/hooks/discovery/init
A PR to set the studio URL at initialisation. This makes the discovery plugin more ready out of the box for other services (e.g. publisher MFE). 
See [thread](https://discuss.overhang.io/t/updating-base-configuration-for-tutor-discovery/1963/3).
@overhangio/tutor-developers this is ready for review.
=> Set studio-url at initialisation

tutordiscovery/patches/local-docker-compose-dev-services
This ensures that services started with `tutor dev start`
are as capable for breakpoint debugging, et al, as services
started with `tutor dev runserver` are. We plan to remove
`tutor dev runserver`.
Blocks https://github.com/overhangio/tutor/pull/644
=> feat: open stdin & allocate tty on dev services

tutordiscovery/templates/discovery/build/discovery/Dockerfile
Makes it possible to build the `discovery` image with a custom NPM_REGISTRY url.
Same fix filed for other plugins.
FYI @regisb
=> fix(build): load NPM_REGISTRY from config

README.rst, tutordiscovery/plugin.py, tutordiscovery/templates/discovery/build/discovery/Dockerfile
Add option to install extra pip requirements.
As part of implementing event_bus_redis, we want the ability to install event_bus_redis in discovery if required. This would allow us to remove kafka and redis event bus deps from discovery and install only if required.
=> feat: extra pip requirements

changelog.d/20230909_160414_i_atlas.md, tutordiscovery/plugin.py, tutordiscovery/templates/discovery/build/discovery/Dockerfile
Add https://github.com/openedx/openedx-atlas to the Dockerfile and run the `atlas pull` command on every build.
I'm starting here because this is a simple plugin and helps us to design it properly. The end goal is to add `atlas` on all other components including edX Platform, MFEs and possibly even ecommerce.
This is a very minimal build that needs the following to be viable:
- Ability to configure the repo, branch and other options.
- Possibly make it a system-wide pattern in tutor instead of adding it to individual components.
This PR requires the following branch of discovery: https://github.com/openedx/course-discovery/pull/4037
<details><summary>Building and testing logs</summary>
```
$ tutor config save
$ tutor images build discovery
Building image …
```
=> feat: add minimal `atlas` step to the build FC-0012

tutordiscovery/templates/discovery/build/discovery/Dockerfile
[course-discovery now maintains its own base.in requirement for atlas](https://github.com/openedx/course-discovery/pull/4117/files#diff-eec14310e29cef9d8ae421c606788e73774112c68cda8ab743ad4257ff73d156R562) the tutor-discovery no longer needs to install it.
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
=> chore: use course-discovery openedx-atlas requirement | FC-0012

README.rst
close #42 as this is not an issue, updating readme in case of confusion.
=> doc: add instructions related to programs

changelog.d/20240220_173703_cmltawt0_mounts.md, tutordiscovery/patches/local-docker-compose-dev-services
This PR is adding the ability to do a local development for course-discovery.
How to test:
```
tutor mounts add ./src/course-discovery
cat root/env/dev/docker-compose.yml
tutor dev start -d discovery
```
=> Add mounts for docker-compose-dev-services

.github/workflows/test.yml, changelog.d/20240313_150946_danyal.faheem_upgrade_to_python_3_12.md
The plugin was already compatible with Python 3.12 after this [commit](https://github.com/overhangio/tutor-discovery/commit/b8f6ad8c9c0110931fb90f38529008e354fd1b5f).
I have just updated the workflows for both python 3.8 and python 3.12 as mentioned [here](https://github.com/overhangio/cookiecutter-tutor-plugin/issues/30#issuecomment-1966466502). 
However, the dockerfile is still to be updated for python 3.12.
=> ci: add python 3.12 in test workflow

README.rst
The site-configuration url was pointing to a non existent link as it was missing the `admin` path. I've just added the admin keyword to the URL and it is working now.
=> docs: fix admin panel site-configuration url

changelog.d/20240412_140658_andres.md, tutordiscovery/templates/discovery/build/discovery/Dockerfile
If the media directory does not exist at the time that uwsgi is launched, the mapping to /media to serve
media files will not be created.
See issue #69
=> fix: Create media directory in Dockerfile.

changelog.d/20240314_131222_faraz.maqsood_python_upgrade_to_v3_12_2.md, tutordiscovery/templates/discovery/build/discovery/Dockerfile
=> Enhancement: Python 3.12 upgrade

README.rst
`Show Programs Tab` wasn't rendering as expected. 
And causing below error on PyPI.
```
ERROR    `long_description` has syntax errors in markup and would not be        
rendered on PyPI.                                                      
line 76: Warning: Title underline too short.                           
Show Programs Tab                                                      
~~~~~~~~~~~~~~~~                                            
```
=> fix: readme correction

changelog.d/20240626_115731_faraz.maqsood_images_persistance_issue.md, tutordiscovery/patches/local-docker-compose-dev-services, tutordiscovery/patches/local-docker-compose-services, tutordiscovery/templates/discovery/build/discovery/Dockerfile
Images were getting disappeared from discovery.
Reproduced this issue by 
- stopping discovery container
- deleting the container
- starting it again
Reason: Media root/directory wasn't added in the volumes.
=> Fix: images does not persist issue

changelog.d/20240710_160247_evgen.dyudyunov_fix_service_user_permissions.md, tutordiscovery/templates/discovery/tasks/lms/init
Grant staff permissions to the catalog_service_user to
fix 403 error during the pathways fetching.
Note: this issue is also described in the readme.
Related discussions:
- https://discuss.openedx.org/t/tutor-discovery-service-api-v1-pathways-403/7995
- https://discuss.openedx.org/t/tutor-discovery-program-issue/10283Grant staff permissions to the catalog_service_user to
fix 403 error during the pathways fetching.
Note: this issue is also described in the readme.
Related discussions:
- https://discuss.openedx.org/t/tutor-discovery-service-api-v1-pathways-403/7995
- https://discuss.openedx.org/t/tutor-discovery-program-issue/10283
=> fix: pathway API permissions

README.rst
This will clean up the README file to follow the RST format, fixed some typos, and improve readability.
Close #81
=> reformat: RST syntax

.github/workflows/test.yml, changelog.d/20241111_172041_faraz.maqsood_remove_py38_references.md, setup.py
Achieves part of https://github.com/overhangio/tutor/issues/1129.
- Update python 3.8 references to 3.9
- Use Github actions to use 3.9
- Ensure tests are working as expected on 3.9
=> chore: remove Python 3.8 references

Makefile, changelog.d/20241122_121506_faraz.maqsood_sumac.md, tests/test_utils.py, tutordiscovery/plugin.py, tutordiscovery/utils.py
- move is_docker_rootless method from tutor to tutor-discovery
- move is_docker_rootless related tests from tutor to tutor-discovery and modify makefile according to it.
=> chore: move is_docker_rootless from tutor to tutor discovery

README.rst, changelog.d/20250108_184343_faraz.maqsood_add_support_for_consuming_events_from_event_bus.md, tutordiscovery/templates/discovery/build/discovery/Dockerfile
- add support to consume events from event bus in discovery. Explanation can be viewed here: https://github.com/openedx/event-bus-redis/blob/main/docs/tutor_installation.rst
- close https://github.com/overhangio/tutor-discovery/issues/94
=> Enhancement: add support for consuming events from event bus in discovery

changelog.d/20250324_230121_danyal.faheem_remove_site_configuration_script.md, tutordiscovery/templates/discovery/tasks/lms/init
Fixes part of https://github.com/overhangio/tutor/issues/1207.
The site-configuration script was used to set the value of the COURSE_CATALOG_API_URL.
However, this script is being removed in tutor core as it is no longer required.
For this reason, we migrate to the provided [create_or_update_site_configuration](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/site_configuration/management/commands/create_or_update_site_configuration.py) management command in edx-platform.
=> chore: replace site-configuration script with management command
